spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/lemonade_oauth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
  mvc:
    #配置统一404异常
    throw-exception-if-no-handler-found: true
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: lemonadeCloud123456
management:
  endpoint:
    health:
      enabled: true
